#!/usr/bin/bash

export NVIM_APPNAME=taskwar
TASKDATA="$XDG_CONFIG_HOME/$NVIM_APPNAME"
TASKRC="$TASKDATA/.taskrc"

mkdir -p "$TASKDATA"
echo "data.location=$TASKDATA" > "$TASKRC"
echo "verbose=blank,footnote,label,new-id,affected,edit,special,project,sync,unwait" >> "$TASKRC"

if task list ; then
    echo "Already initialized"
else
  task add project:Introduction +intro First task
fi

cd "$TASKDATA" || exit
touch "$TASKDATA/scratch"

# Dev reasons
NVIM_APPNAME=nvimata/taskwar nvim scratch
